language: python
python:
  - "2.7"
  - "3.6"
addons:
    firefox: "34.0"
install:
  - "bash install-bmp.sh"
  - "pip install flake8"
  - "pip install -r requirements.txt"
before_script:
  - "flake8 ."
script:
  - "python test_harprofiler.py"
